apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo12.fullname" . }}-service
  labels:
    {{- include "demo12.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "demo12.selectorLabels" . | nindent 4 }}